### ISSUE TITLE
ready for device returns Error on agent not ready

### ISSUE THREAD

**Issue by kelvissu** [haydenbleasel/corellium-typescript#19]
`const ready = await corellium.device('deviceId').ready();`
When run on a IOS device in creation returns the following:
```
Error: Agent not yet available.
    at Object.ready (/home/kelvissu/source/ui-test/node_modules/corellium-typescript/dist/index.js:1:23764)
    at async CorelliumTs.areyouready (/home/kelvissu/source/ui-test/test/helpers/corellium-ts.ts:56:19)
    at async Context.<anonymous> (/home/kelvissu/source/ui-test/test/specs/ios_device.ts:46:5)
```

This is because the method throws an error when the agent isn't available. Should this be doing this? I believe it should instead return `{ ready: false }` so that we can detect when the agent is ready.

**Comment by haydenbleasel** [comment]
Fixed - no need for a try catch anymore and the `ready()` command returns the boolean instead of `{ ready: boolean }`
